name: Maha Master Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with: { distribution: 'zulu', java-version: '17' }
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with: { gradle-version: '8.4' }
      - name: Build Application
        run: gradle assembleDebug
      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: Maha-App-Final
          path: app/build/outputs/apk/debug/app-debug.apk
